---
resources:
- name: broker-parent
  type: git
  source:
    uri: https://github.com/robertgmoss/spring-boot-cf-service-broker
    branch: async

- name: brooklyn-broker
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/brooklyn-service-broker
    branch: master

- name: service-broker-binary
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: brooklyn-service-broker
    access_token: {{github-access-token}}

jobs:
- name: build-broker
  public: true
  plan:
  - aggregate:
    - get: broker-parent
    - get: brooklyn-broker
      trigger: true
  - task: build-and-test-broker
    file: brooklyn-broker/ci/build-and-test-broker.yml
  - put: service-broker-binary
    params:
      name: brooklyn-broker/release/name
      tag: brooklyn-broker/release/tag
      body: brooklyn-broker/release/body
      globs:
        - "build-and-test-broker/brooklyn-broker/build/libs/brooklyn-broker-*.war"

