---
resources:

- name: brooklyn-broker
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/brooklyn-service-broker
    branch: master

- name: service-broker-binary
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: brooklyn-service-broker
    access_token: {{github-access-token}}

jobs:
- name: build-broker
  public: true
  plan:
  - get: brooklyn-broker
    trigger: true
  - task: build-and-test-broker
    file: brooklyn-broker/ci/build-and-test-broker.yml
  - put: service-broker-binary
    params:
      name: brooklyn-broker/release/name
      tag: brooklyn-broker/release/tag
      globs:
        - "built-brooklyn-broker/brooklyn-broker-*.war"

